sudo: required

language: php
php:
  - '7.0'

services:
- docker

before_install:
  - docker build -t schulcloud/meta-search-engine .
  - docker run -d -p 8000:80 --name meta-search-engine-container schulcloud/meta-search-engine

before_script:
  # install packages
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq python3 python3-pip
  - pip3 install --user schul-cloud-search-tests

script:
  - "curl -i -H 'User-Agent: python-requests/2.18.1' -H 'Accept-Encoding: gzip, deflate' -H 'Host: localhost:37325' -H 'Accept: */*' 'http://localhost:8000/?Q=test'"
  - "python3 -m schul_cloud_search_tests.search --url=http://localhost:8000/"

after_failure:
  - docker logs meta-search-engine-container


